- .github/workflows/mainnet.yml
- .github/workflows/testnet.yml
- Install estlint packages when building on CI
Can build on develop branch
> Feature/Configure eslint packages on CI

- .github/workflows/mainnet.yml
- .github/workflows/testnet.yml
- README.md
- client/package.json
- client/src/helpers/currency.js
- client/src/helpers/currency.test.js
- Run UT on develop and master branch
- Upload code coverage to codecov 
- Show the codecov badge on README
> Feature/run UT on CI

- client/src/actions/NFTActions.js
- client/src/actions/NFTActions.test.js
- client/src/actions/tokensActions.js
- client/src/actions/tokensActions.test.js
- client/src/components/NFTs/index.jsx
- client/src/constants/tokens.js
- client/src/selectors/NFTs.js
- client/src/selectors/NFTs.test.js
- client/src/selectors/tokens.js
- client/src/selectors/tokens.test.js
-   [x] All unit tests must be passed
> Update token config

- client/src/components/Common/Layout/Stake/DelegateForm.jsx
- client/src/components/Common/Layout/Stake/DelegateForm.test.jsx
- client/src/components/Common/SendReceive/index.jsx
- client/src/components/Common/SendReceive/index.test.jsx
- client/src/services/userServices.js
- Should minus fee when click preset button
- 
> update preset button logic

- client/src/components/hooks/useAutoRefreshEffect.js
- client/src/selectors/NFTs.js
- fix issue when adding custom contract
> fix issue when adding custom contract

- client/src/components/NFTs/NFTModal.jsx
- client/src/components/NFTs/index.jsx
https://github.com/CasperDash/casperdash-api/pull/19
> support casperpunk nft

- client/src/components/Common/Layout/Stake/DelegateForm.jsx
- client/src/components/Common/Layout/Stake/DelegateForm.test.jsx
- client/src/components/Common/Layout/Stake/Modal.jsx
- client/src/components/Common/Layout/Stake/Modal.test.jsx
- client/src/components/Common/Layout/Stake/UnDelegateForm.jsx
- client/src/components/Common/Layout/Stake/UnDelegateForm.test.jsx
- client/src/components/__mocks__/react-router-dom.js
- client/src/components/web-extension/Dashboard/index.test.jsx
- client/src/components/web-extension/DeployDetails/index.test.jsx
- client/src/components/web-extension/Market/index.test.jsx
- client/src/components/web-extension/Staking/Confirm.jsx
- client/src/components/web/NFTs/CreateNFTs/DeployConfirmModal.jsx
- client/src/components/web/NFTs/NFTModal.jsx
- client/src/services/ledgerServices.js
- Fix issue that confirm popup did not close after successfully deploy
- Fix Mint button on review NFT modal
- Update ledger error message
> fix staking issue

- client/src/services/stakeServices.js
> HOT-FIX fix staking deploy

- client/src/components/Common/Layout/Stake/DelegateForm.test.jsx
- client/src/constants/key.js
> Update delegate fee

- client/src/actions/createWalletActions.utils.js
- client/src/components/web-extension/CreateWallet/ValidateKeyphrasePage.jsx
Fix up selected words for validation were always first 4 words
-   [X ] I removed all commented or unnecessary code.
-   [X] Provide the screenshots due to UI changed or bug fixed
> UPDATE: - Fix up selected words were always first 4 words

- client/src/actions/userActions.js
- client/src/actions/userActions.test.js
- client/src/services/localStorage.chrome.test.js
- client/src/services/localStorage.js
- client/src/store/index.js
Fixing errors when calling `chrome` in non-webkit browsers
-   [X ] I removed all commented or unnecessary code.
-   [X] Provide the screenshots due to UI changed or bug fixed
-   [X] My code has covered these test cases (please list down your tested cases):
> UPDATE: - Fix chrome is not defined in non-webkit browsers

- client/src/components/web-extension/Common/Grid/index.jsx
- client/src/components/web-extension/Dashboard/index.jsx
The CSPR price drop to 2~3 cent, so we need to update the decimal places to 4
> fix cspr price decimal places

- client/src/components/web-extension/Common/CopyButton/index.jsx
- client/src/components/web-extension/CreateWallet/RecoveryPhrasePage.jsx
- client/src/components/web-extension/CreateWallet/RecoveryPhrasePage.scss
- Create CopyButton component
Task: #136 
> Feat: #136 Implement copy recovery phrase button

- client/src/components/hooks/useGetWallets.js
- client/src/components/web-extension/Common/Account/AccountManagerModal.jsx
- client/src/components/web-extension/Common/Account/AccountManagerModal.scss
- client/src/components/web-extension/Common/Account/useWallets.js
- client/src/helpers/balance.js
- client/src/helpers/format.js
- client/src/services/ServiceWorker/Controllers/AccountController.js
- client/src/services/request.js
- client/src/services/userServices.js
- Display the balance of wallets
> Refactor: #110 Display balance wallets

- client/src/components/Common/ConfirmModal/ConfirmModal.scss
- client/src/components/Common/ConfirmModal/index.jsx
- client/src/components/web-extension/Settings/SettingRow.jsx
- client/src/components/web-extension/Settings/index.jsx
- client/src/components/web-extension/Settings/index.scss
> Feat: #133 Confirmation popup when clear all data

- client/src/app/web-extension/App.scss
- client/src/components/web-extension/Common/Header/OuterHeader.jsx
- client/src/components/web-extension/ConnectAccount/index.jsx
- client/src/components/web-extension/Dashboard/index.scss
> Feat: #154 Open new tab when creating new wallet

- client/src/components/web-extension/Common/Header/OuterHeader.jsx
- client/src/components/web-extension/Common/Header/OuterHeader.test.jsx
- Add the condition to show the header on `OuterHeader` component
> Fix: #146 do not show header on /connectAccount path

- client/src/components/web-extension/Common/Header/OuterHeader.test.jsx
- Update UT for OutHeader with back button case
> Test: #154 not show header case

- client/src/store/index.js
- client/src/store/reducers/userReducer.js
Root cause:
- Overwrite `Initial state` from persistent redux
Solution:
- Consistent `Initial state` between persistent and default
> Fix: #163 selected account does not highlight when clear local storage

- client/src/app/web-extension/App.js
- client/src/components/hooks/useServiceWorker.js
- client/src/services/ServiceWorker/serviceWorker.js
As we inject scripts to open tabs so no need to repeatedly post message to SW
> remove keep alive message

- .github/workflows/check.yml
- client/package.json
- client/src/actions/userActions.js
- client/src/actions/userActions.test.js
- client/src/components/Common/ConfirmModal/ConfirmModal.scss
- client/src/components/Common/ConfirmModal/index.jsx
- client/src/components/Common/Layout/HeadingComponent/Heading.jsx
- client/src/components/hocs/ServiceWorkerRequired/index.jsx
- client/src/components/hooks/useGetWallets.js
- client/src/components/web-extension/Common/Account/AccountManagerModal.jsx
- client/src/components/web-extension/Common/Account/index.jsx
- client/src/components/web-extension/Common/AuthLogin/index.jsx
- client/src/components/web-extension/Common/DeleteAllDataButton/index.jsx
- client/src/components/web-extension/ConnectAccount/index.jsx
- client/src/components/web-extension/Send/SendForm.jsx
- client/src/components/web-extension/Settings/SettingRow.jsx
- client/src/components/web-extension/Settings/index.jsx
- client/src/components/web-extension/Settings/index.scss
- client/src/selectors/user.js
- client/src/store/reducers/userReducer.test.js
- client/yarn.lock
> Fix: #161 Delete all data button is not correct style

- client/src/app/web-extension/routeConfig.js
- client/src/components/hooks/useServiceWorker.js
- client/src/components/web-extension/Common/LoginModal/LoginModalForm.jsx
- client/src/components/web-extension/Common/LoginModal/index.jsx
- client/src/components/web-extension/RecoveryPhrase/RecoveryPhrase.scss
- client/src/components/web-extension/RecoveryPhrase/index.jsx
- client/src/components/web-extension/Settings/SettingRow.jsx
- client/src/components/web-extension/Settings/index.jsx
- client/src/services/ServiceWorker/Controllers/AccountController.js
- client/src/services/ServiceWorker/serviceWorker.js
- client/src/services/UserService.js
- Show recovery phrase password in setting
- Require a password when user click
> Feat: #162 show recovery phrase password

- client/.babelrc
- client/src/app/web-extension/App.js
- client/src/components/Common/Auth/useWithAccount.js
- jsconfig.json
> check account status on for outer routes

- client/package.json
- client/src/components/Common/Auth/useWithAccount.test.js
> fix unit test

- client/src/actions/userActions.js
- client/src/actions/userActions.test.js
- client/src/app/web-extension/App.js
- client/src/components/Common/Auth/useWithAccount.js
- client/src/components/Common/ConfirmModal/index.jsx
- client/src/components/hocs/ServiceWorkerRequired/index.jsx
- client/src/components/hooks/useLockAccountWhenIdle.js
- client/src/components/hooks/useServiceWorker.js
- client/src/components/web-extension/Common/Account/AccountManagerModal.jsx
- client/src/components/web-extension/Common/LoginModal/EnterPasswordModal.jsx
- client/src/components/web-extension/Common/LoginModal/LoginModalConfirm.jsx
- client/src/components/web-extension/Common/LoginModal/LoginModalForm.jsx
- client/src/components/web-extension/WelcomeBack/WelcomeBackPage.jsx
- client/src/services/ServiceWorker/MessageChannel.js
- client/src/services/ServiceWorker/serviceWorker.js
> clean up + fix issue that sometime cant unlock wallet

- client/src/actions/userActions.js
- client/src/actions/userActions.test.js
- client/src/components/web-extension/Common/Account/index.jsx
- client/src/components/web-extension/Common/DeleteAllDataButton/index.jsx
- client/src/services/localStorage.js
Delete all data didn't clear the storage before, update to fix it
> fix delete all data

- client/src/components/Common/MultilineTruncatedText/MultilineTruncatedText.scss
- client/src/components/Common/MultilineTruncatedText/index.jsx
- client/src/components/web-extension/ConnectedSites/index.jsx
- client/src/components/web-extension/DappConnection/index.scss
- client/src/components/web-extension/DappSignDeployRequest/index.jsx
- client/src/components/web-extension/DappSignDeployRequest/index.scss
- client/src/components/web-extension/DappSignMessageRequest/index.jsx
- client/src/components/web-extension/DappSignMessageRequest/style.scss
- client/src/services/ServiceWorker/Controllers/PopupController.js
- client/src/services/ServiceWorker/utils.js
- Move the popup to the right side
> Feat: #193 Move popup to right side

- client/src/services/nftServices.js
> Fix transfer nft

- client/src/components/hocs/DappConnectorRequired/index.jsx
- client/src/components/hooks/useServiceWorker.js
- client/src/components/web-extension/DappConnection/index.jsx
- client/src/components/web-extension/DappSignDeployRequest/index.jsx
- client/src/components/web-extension/DappSignMessageRequest/index.jsx
- client/src/services/ServiceWorker/Controllers/PopupController.js
- client/src/services/ServiceWorker/serviceWorker.js
- Prevent dApp URL access by extension full screen
> feat: #193 Prevent dApp URL

- client/src/services/ServiceWorker/utils.js
- Error parsing with transfer CSPR
> Fix: #193 DApp Connector error parsing

- client/src/services/nftServices.js
> Fix cannot transfer cep47 with list of u256

- client/src/content/inpage.js
> Refactor: Rename casperDash dapp

- client/src/content/inpage.js
- client/src/services/ServiceWorker/Controllers/AccountController.js
- client/src/services/ServiceWorker/Controllers/PopupController.js
- client/src/services/UserService.js
> Chore: Remove logs

- client/src/assets/image/check-alt.svg
- client/src/assets/image/close-icon-alt.svg
- client/src/components/hooks/useGetWallets.js
- client/src/components/hooks/useServiceWorker.js
- client/src/components/web-extension/Common/Account/AccountManagerModal.jsx
- client/src/components/web-extension/Common/Account/AccountManagerModal.scss
- client/src/services/ServiceWorker/Controllers/AccountController.js
- client/src/services/ServiceWorker/Controllers/SigningController.js
- client/src/services/ServiceWorker/serviceWorker.js
- client/src/services/UserService.js
Add button to edit account name
> Edit account name

- .github/workflows/check.yml
- client/src/app/web-extension/routeConfig.js
- client/src/components/hocs/DappConnectorRequired/index.jsx
- client/src/components/hocs/ServiceWorkerRequired/index.jsx
- client/src/components/hooks/useLedger.js
- client/src/components/hooks/useLedger.test.js
- client/src/components/hooks/useLockAccountWhenIdle.js
- client/src/components/web-extension/Common/Account/AccountManagerModal.jsx
- client/src/components/web-extension/Common/DeleteAllDataButton/index.jsx
- client/src/components/web-extension/Common/Header/Header.scss
- client/src/components/web-extension/DappConnection/index.jsx
- client/src/components/web-extension/Ledger/Warning.jsx
- client/src/components/web-extension/Ledger/warning.scss
- client/src/components/web-extension/Send/SendForm.jsx
- client/src/components/web-extension/Settings/Index.test.jsx
- client/src/components/web-extension/Settings/index.jsx
- client/src/selectors/user.js
- client/src/services/ServiceWorker/serviceWorker.js
> Fix - show warning message if connect dapp by ledger

- .github/workflows/check.yml
- client/src/helpers/extension/signing.js
- client/src/services/ServiceWorker/Controllers/PopupController.js
- client/src/services/ServiceWorker/Controllers/SigningController.js
- Fix undefined function `verifyTargetAccountMatch` and `sanitiseNestedLists` when parsing deploy
> Fix: Undefined function to parse deploy

- client/src/app/web-extension/App.js
- client/src/components/hooks/useLockAccountWhenIdle.js
- client/src/components/hooks/useServiceWorker.js
- client/src/services/ServiceWorker/serviceWorker.js
- Root cause:
- `browser` undefined
- Solution: 
- Retry to load browser with interval
> Fix: Auto lock can not run correct

- client/src/services/ServiceWorker/UserService.js
- Should await for promise function
> Refactor: Await when adding wallet

- client/src/components/web-extension/Liquidity/LiquidityForm/ConfirmButton/index.jsx
- client/src/components/web-extension/Liquidity/hooks.js
- client/src/services/tokenServices.js
- Can add liquid send if the contract is not approved
> Fix: Approve on Liquid Contract

- .github/workflows/check.yml
- client/jest.config.js
- client/package.json
- client/src/__mocks__/fileMock.js
- client/src/components/Common/Auth/useWithAccount.js
- client/src/components/web-extension/Dashboard/index.test.jsx
- client/webpack/commonConfig.js
- client/yarn.lock
> Fix: Yarn dependencies audit

- client/src/components/web-extension/Common/Account/PrivateKey.jsx
- client/src/components/web-extension/Common/Account/PrivateKey.scss
- Blur the private key and add copy button
> Fix: Blur private key and copy

- client/template/extension/manifest.json
- Define content security policy
Related issue #257 
> Fix: Content security policy

- client/template/extension/manifest.json
- Allow connecting src for external URLs
Related task #257 
> Fix: Allow list connect src for external urls

- client/src/assets/image/copy-icon.svg
- client/src/components/Common/Button/Copy.jsx
- client/src/components/Common/Button/Copy.scss
- client/src/components/web-extension/Common/Account/index.jsx
- Copy button bug  with hover with tooltip -> Change to popover and revamp css
> Fix: Copy button bug UI

- client/src/actions/priceActions.js
- client/src/actions/priceActions.test.js
- client/src/selectors/price.js
- client/template/extension/manifest.json
> Refactor: Get Coingecko history with CasperDash API

- client/src/components/web-extension/Common/Account/PrivateKey.jsx
- client/src/components/web-extension/CreateWallet/RecoveryPhrasePage.jsx
- client/src/components/web-extension/RecoveryPhrase/index.jsx
- Remove copy button on "View Recovery Keys" and "View Private Keys"
> Refactor: HAL-01 Remove copy button for secret keys

- .github/workflows/check.yml
- client/package.json
- client/src/actions/createWalletActions.js
- client/src/components/web-extension/Common/Account/PrivateKey.jsx
- client/src/components/web-extension/Common/CreatePasswordPage/useCreateUser.js
- client/src/components/web-extension/CreateWallet/RecoveryPhrasePage.jsx
- client/src/components/web-extension/CreateWallet/RecoveryPhrasePage.scss
- client/src/components/web-extension/CreateWallet/ValidateKeyphrasePage.jsx
- client/src/components/web-extension/ImportWallet/ImportWalletPage.jsx
- client/src/components/web-extension/RecoveryPhrase/index.jsx
- client/src/helpers/shareable.js
- client/src/selectors/createWallet.js
- client/src/selectors/createWallet.test.js
- client/src/store/reducers/createWallet.js
- client/src/store/reducers/createWallet.test.js
- client/yarn.lock
- Splitting mnemonic phrases to small and don't save original recovery phrases on state/global state
> Refactor: HAL-02 Secure key phrases

- client/src/services/ServiceWorker/Controllers/PopupController.js
- Check user exists before connecting to dApp
> Fix: #272 Require user exist before connect dApp

- client/package.json
- client/yarn.lock
- Update dependencies to avoid security errors
After fix:
> Fix: Yarn audit errors

- client/package.json
- client/src/components/web-extension/CreateWallet/RecoveryPhrasePage.jsx
- client/src/components/web-extension/CreateWallet/ValidateKeyphrasePage.jsx
- client/src/components/web-extension/RecoveryPhrase/index.jsx
- client/src/helpers/shareable.js
- client/yarn.lock
- Unregister const for mnemonic phrases
> Fix: Un-register const for mnemonic phrases

- client/src/helpers/extension/signing.js
- Conflict casper-js-sdk from dApp with older version
> Fix: Public key compare not working

- client/src/services/ServiceWorker/Controllers/AccountController.js
- Check with localstorage instead of variable
> HotFix: Check user exist with local storage

- client/src/components/Common/Auth/useWithAccount.test.js
> Test: Mock nano-id

- client/src/components/web-extension/Send/SendForm.jsx
- Check balance is 0 and set amount to 0
> Fix: #221 Negative number when click on max button

- client/src/components/Common/TooltipText/index.jsx
- client/src/components/Common/TooltipText/index.scss
- client/src/components/web-extension/Common/Grid/index.jsx
- client/src/components/web-extension/Common/SearchValidator/FeeTooltip.jsx
- client/src/components/web-extension/Common/SearchValidator/index.jsx
> Feat: #242 Tooltip to explain the validator fee

- client/src/components/web-extension/Staking/index.jsx
- client/src/helpers/validator.js
> Feat: #307 Message staking

- client/src/components/web-extension/DappSignDeployRequest/index.jsx
- client/src/services/ServiceWorker/Controllers/SigningController.js
> Feat:#270 dApp signing with contract hash

- client/src/components/web-extension/Staking/StakingGrid/StakingInfo.jsx
- client/src/components/web-extension/Staking/StakingGrid/StakingInfo.scss
- client/src/components/web-extension/Staking/StakingGrid/UndelegateButton.jsx
> Feat: #305 Users have no idea how to delegate more cspr

- client/package.json
- client/src/components/hooks/useDeleteAllData.js
- client/src/components/web-extension/Common/AuthLogin/index.jsx
- client/src/components/web-extension/Common/AuthLogin/index.scss
- client/src/components/web-extension/Common/DeleteAllDataLinkConfirm/ConfirmDeleteAllDataModal.jsx
- client/src/components/web-extension/Common/DeleteAllDataLinkConfirm/ConfirmDeleteAllDataModal.scss
- client/src/components/web-extension/Common/DeleteAllDataLinkConfirm/index.jsx
- client/src/components/web-extension/Common/DeleteAllDataLinkConfirm/index.scss
- client/src/components/web-extension/Common/DeleteAllDataNotice/index.jsx
- client/src/components/web-extension/WelcomeBack/WelcomeBack.scss
- client/src/components/web-extension/WelcomeBack/WelcomeBackPage.jsx
- client/yarn.lock
> Feat: #304 Add delete all data button on lock screen

- client/package.json
- client/src/app/web-extension/App.scss
- client/src/components/web-extension/Common/Grid/index.jsx
- client/src/components/web-extension/Common/SearchValidator/index.jsx
- client/yarn.lock
- Apply virtual list to load validators
#326 
> Feat: #326 Virtual list validators

- client/src/components/web-extension/Common/Grid/index.jsx
- client/src/components/web-extension/Staking/StakingGrid/StakingInfo.jsx
- client/src/components/web-extension/Staking/StakingGrid/StakingInfo.scss
- client/src/components/web-extension/Staking/StakingGrid/UndelegateButton.jsx
- client/src/components/web-extension/Staking/StakingGrid/UndelegateButton.scss
> Refactor: #305 Add dropdown staking button with bootstrap

- client/jest.config.js
- client/src/components/web-extension/Common/Account/index.test.jsx
- client/src/components/web-extension/Common/SearchValidator/index.test.jsx
- client/src/components/web-extension/Dashboard/index.test.jsx
- client/src/components/web-extension/Settings/Index.test.jsx
- client/src/components/web-extension/Staking/StakingGrid/UndelegateButton.test.jsx
- client/src/store/reducers/settings.test.js
> Test: Update UT for new features

- client/src/selectors/stake.js
- Check redelegating status and update it
> Fix: Redelegating status

- client/src/selectors/user.js
- Add getNetwork to selector on user redux
> Fix: Get config with selector

- .gitignore
- client/src/components/web-extension/NFTs/components/NFTTransferForm/index.jsx
- Check user total balance before sending
> Fix: #373 should validate network fee

- client/src/components/Common/AccountItem/AccountItem.scss
- client/src/components/hooks/useServiceWorker.js
- client/src/components/web-extension/ConnectedSites/index.jsx
- client/src/components/web-extension/DappConnection/index.jsx
- client/src/components/web-extension/DappConnection/index.scss
- client/src/services/ServiceWorker/Controllers/PopupController.js
- client/src/services/ServiceWorker/serviceWorker.js
- Disconnect all account when user call `casperDashHelper.disconnectFromSite();`
- Update UI for "Connect account"
> Refactor: Disconnect all account from dapp
